apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk1-pv
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: /mr/zk
